# Generated by Django 3.2.25 on 2025-05-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalusers',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='normalusers',
            name='password2',
        ),
    ]
