# Generated by Django 3.2.25 on 2025-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0002_customuser_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='anotherran',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
