# Generated by Django 3.2.25 on 2025-05-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0003_customuser_anotherran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_item_des',
            field=models.TextField(),
        ),
    ]
