# Generated by Django 3.2.25 on 2025-05-13 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0004_alter_fooditem_food_item_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details', models.TextField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('total_quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('from_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.restaurant')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('to_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.fooditem')),
                ('to_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.restaurant')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
