# Generated by Django 3.2.25 on 2025-05-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0005_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_item_price',
            field=models.IntegerField(),
        ),
    ]
