# Generated by Django 3.2.25 on 2025-05-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0006_alter_fooditem_food_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_image',
            field=models.ImageField(default='parcel_icon.png', upload_to='allimages'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Success', 'Success'), ('on-delivery', 'on-delivery')], default='pending', max_length=20),
        ),
    ]
