# Generated by Django 3.2.25 on 2025-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0007_auto_20250513_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_image',
            field=models.ImageField(default='allimages/parcel_icon.png', upload_to='allimages'),
        ),
    ]
