# Generated by Django 5.2.1 on 2025-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0008_alter_order_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('on-delivery', 'on-delivery')], default='Pending', max_length=20),
        ),
    ]
