# Generated by Django 5.2.1 on 2025-05-15 06:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0011_alter_restaurant_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_item_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
